{% set version = "0.1.8" %}
{% set sha256 = "acd675843e2ecd4ad6b8019f64ff296bb3d62fe8bb35ff1b4467e1848d127392" %}

package:
  name: dmtools
  version: {{ version }}

source:
  url: https://github.com/ZhouQiangwei/dmtools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib
    - perl

test:
  commands:
    - dmtools 2>&1 | grep "Command Format :  dmtools"

about:
  home: https://github.com/ZhouQiangwei/dmtools
  license: GPL3
  license_file: COPYING
  summary: BS-seq, WGBS, NOMe-Seq, RRBS data storage and analysis tool.

extra:
  identifiers:
    - biotools:dmtools
