{% set name = "dmtools" %}
{% set version = "0.2.2" %}
{% set sha256 = "8c2187f06574c544715fec2ba82e8c0cdae3048d6d3180e70411c708c4d674f3" %}

package:
  name: "{{ name|lower }}"
  version: {{ version }}

source:
  url: https://github.com/ZhouQiangwei/dmtools/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('dmtools', max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - curl
    - zlib
    - libcurl
    - htslib
  run:
    - htslib
    - zlib
    - libcurl
    - perl

test:
  commands:
    - dmtools 2>&1 | grep "Command Format :  dmtools"

about:
  home: https://github.com/ZhouQiangwei/dmtools
  license: GPL3
  license_file: COPYING
  summary: BS-seq, WGBS, NOMe-Seq, RRBS data storage and analysis tool dmtools
